name: "Hello World Workflow"

# workflow will trigger whenever you push to any branch in the repository.
on:
  push:

    
jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: "Print hello world"
        run: echo "Hello World"

      - name: "Print current date"
        run: date